<a href="https://www.kaggle.com/code/samyakb/eda-using-anova?scriptVersionId=167836271" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv("/kaggle/input/playground-series-s4e3/train.csv")
train = train.set_index('id')
test = pd.read_csv("/kaggle/input/playground-series-s4e3/test.csv")
test = test.set_index('id')
train.head()

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
id                                                                          
0         584        590     909972     909977            16            8   
1         808        816     728350     728372           433           20   
2          39        192    2212076    2212144         11388          705   
3         781        789    3353146    3353173           210           16   
4        1540       1560     618457     618502           521           72   

    Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
id                                                          
0             5               2274                    113   
1            54              44478                     70   
2           420            1311391                     29   
3            29               3202                    114   
4            67              48231                     82   

    Maximum_of_Luminosity  ...  Orientation_Index  Luminosity_Index  \
id                         ...                                        
0                     140  ...            -0.5000           -0.0104   
1                     111  ...             0.7419           -0.2997   
2                     141  ...            -0.0105           -0.0944   
3                     134  ...             0.6667           -0.0402   
4                     111  ...             0.9158           -0.2455   

    SigmoidOfAreas  Pastry  Z_Scratch  K_Scatch  Stains  Dirtiness  Bumps  \
id                                                                          
0           0.1417       0          0         0       1          0      0   
1           0.9491       0          0         0       0          0      0   
2           1.0000       0          0         1       0          0      0   
3           0.4025       0          0         1       0          0      0   
4           0.9998       0          0         0       0          0      0   

    Other_Faults  
id                
0              0  
1              1  
2              0  
3              0  
4              1  

[5 rows x 34 columns]

In [3]:
train.dtypes

X_Minimum                  int64
X_Maximum                  int64
Y_Minimum                  int64
Y_Maximum                  int64
Pixels_Areas               int64
X_Perimeter                int64
Y_Perimeter                int64
Sum_of_Luminosity          int64
Minimum_of_Luminosity      int64
Maximum_of_Luminosity      int64
Length_of_Conveyer         int64
TypeOfSteel_A300           int64
TypeOfSteel_A400           int64
Steel_Plate_Thickness      int64
Edges_Index              float64
Empty_Index              float64
Square_Index             float64
Outside_X_Index          float64
Edges_X_Index            float64
Edges_Y_Index            float64
Outside_Global_Index     float64
LogOfAreas               float64
Log_X_Index              float64
Log_Y_Index              float64
Orientation_Index        float64
Luminosity_Index         float64
SigmoidOfAreas           float64
Pastry                     int64
Z_Scratch                  int64
K_Scatch                   int64
Stains    

In [4]:
train.isna().sum()

X_Minimum                0
X_Maximum                0
Y_Minimum                0
Y_Maximum                0
Pixels_Areas             0
X_Perimeter              0
Y_Perimeter              0
Sum_of_Luminosity        0
Minimum_of_Luminosity    0
Maximum_of_Luminosity    0
Length_of_Conveyer       0
TypeOfSteel_A300         0
TypeOfSteel_A400         0
Steel_Plate_Thickness    0
Edges_Index              0
Empty_Index              0
Square_Index             0
Outside_X_Index          0
Edges_X_Index            0
Edges_Y_Index            0
Outside_Global_Index     0
LogOfAreas               0
Log_X_Index              0
Log_Y_Index              0
Orientation_Index        0
Luminosity_Index         0
SigmoidOfAreas           0
Pastry                   0
Z_Scratch                0
K_Scatch                 0
Stains                   0
Dirtiness                0
Bumps                    0
Other_Faults             0
dtype: int64

In [5]:
from statsmodels.multivariate.manova import MANOVA
from statsmodels.formula.api import ols
import statsmodels.api as sm
import statsmodels.stats.multicomp as mc
import scipy.stats as stats

independent_cols = test.columns.tolist()
for c in independent_cols:
    min_value = train[c].min()
    max_value = train[c].max()
    train[c+"_scaled"] = (train[c] - min_value) / (max_value - min_value)
    test[c+"_scaled"] = (test[c] - min_value) / (max_value - min_value)

In [6]:
train.columns

Index(['X_Minimum', 'X_Maximum', 'Y_Minimum', 'Y_Maximum', 'Pixels_Areas',
       'X_Perimeter', 'Y_Perimeter', 'Sum_of_Luminosity',
       'Minimum_of_Luminosity', 'Maximum_of_Luminosity', 'Length_of_Conveyer',
       'TypeOfSteel_A300', 'TypeOfSteel_A400', 'Steel_Plate_Thickness',
       'Edges_Index', 'Empty_Index', 'Square_Index', 'Outside_X_Index',
       'Edges_X_Index', 'Edges_Y_Index', 'Outside_Global_Index', 'LogOfAreas',
       'Log_X_Index', 'Log_Y_Index', 'Orientation_Index', 'Luminosity_Index',
       'SigmoidOfAreas', 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains',
       'Dirtiness', 'Bumps', 'Other_Faults', 'X_Minimum_scaled',
       'X_Maximum_scaled', 'Y_Minimum_scaled', 'Y_Maximum_scaled',
       'Pixels_Areas_scaled', 'X_Perimeter_scaled', 'Y_Perimeter_scaled',
       'Sum_of_Luminosity_scaled', 'Minimum_of_Luminosity_scaled',
       'Maximum_of_Luminosity_scaled', 'Length_of_Conveyer_scaled',
       'TypeOfSteel_A300_scaled', 'TypeOfSteel_A400_scaled',
       'Steel_P

In [7]:
independent_cols_scaled = test.columns.tolist()
independent_cols_scaled

['X_Minimum',
 'X_Maximum',
 'Y_Minimum',
 'Y_Maximum',
 'Pixels_Areas',
 'X_Perimeter',
 'Y_Perimeter',
 'Sum_of_Luminosity',
 'Minimum_of_Luminosity',
 'Maximum_of_Luminosity',
 'Length_of_Conveyer',
 'TypeOfSteel_A300',
 'TypeOfSteel_A400',
 'Steel_Plate_Thickness',
 'Edges_Index',
 'Empty_Index',
 'Square_Index',
 'Outside_X_Index',
 'Edges_X_Index',
 'Edges_Y_Index',
 'Outside_Global_Index',
 'LogOfAreas',
 'Log_X_Index',
 'Log_Y_Index',
 'Orientation_Index',
 'Luminosity_Index',
 'SigmoidOfAreas',
 'X_Minimum_scaled',
 'X_Maximum_scaled',
 'Y_Minimum_scaled',
 'Y_Maximum_scaled',
 'Pixels_Areas_scaled',
 'X_Perimeter_scaled',
 'Y_Perimeter_scaled',
 'Sum_of_Luminosity_scaled',
 'Minimum_of_Luminosity_scaled',
 'Maximum_of_Luminosity_scaled',
 'Length_of_Conveyer_scaled',
 'TypeOfSteel_A300_scaled',
 'TypeOfSteel_A400_scaled',
 'Steel_Plate_Thickness_scaled',
 'Edges_Index_scaled',
 'Empty_Index_scaled',
 'Square_Index_scaled',
 'Outside_X_Index_scaled',
 'Edges_X_Index_scaled',
 

In [8]:
from statsmodels.multivariate.manova import MANOVA

# Assuming 'Response_Variable' is the dependent variable you are interested in
dependent_variable = 'Pastry+Z_Scratch+K_Scatch+Stains+Dirtiness+Bumps+Other_Faults'

# Creating the formula for MANOVA
formula = f'{dependent_variable} ~ {" + ".join(independent_cols_scaled)}'

# Creating the MANOVA object
manova = MANOVA.from_formula(formula, data=train)

# Printing the MANOVA results
print(manova.mv_test())


                      Multivariate linear model
                                                                     
----------------------------------------------------------------------
         Intercept         Value   Num DF    Den DF    F Value  Pr > F
----------------------------------------------------------------------
            Wilks' lambda  0.9989  7.0000  19158.0000   2.8831  0.0052
           Pillai's trace  0.0011  7.0000  19158.0000   2.8831  0.0052
   Hotelling-Lawley trace  0.0011  7.0000  19158.0000   2.8831  0.0052
      Roy's greatest root  0.0011  7.0000  19158.0000   2.8831  0.0052
---------------------------------------------------------------------
                                                                     
----------------------------------------------------------------------
         X_Minimum         Value   Num DF    Den DF    F Value  Pr > F
----------------------------------------------------------------------
            Wilks' lambda  0.999

In [9]:

    
    var_drop=(['Edges_Index', 
             'Outside_X_Index', 
             'Outside_Global_Index', 
             'Luminosity_Index', 
             'SigmoidOfAreas', 
             'X_Minimum_scaled', 
             'X_Maximum_scaled', 
             'Y_Minimum_scaled', 
             'Y_Perimeter_scaled', 
             'Sum_of_Luminosity_scaled', 
             'TypeOfSteel_A400_scaled', 
             'Edges_Index_scaled', 
             'Outside_X_Index_scaled', 
             'Outside_Global_Index_scaled', 
             'Luminosity_Index_scaled', 
             'SigmoidOfAreas_scaled',
             'Y_Minimum',
             'Y_Maximum', 
             'TypeOfSteel_A400',
             'TypeOfSteel_A300',
             'X_Perimeter',
             'X_Minimum',
             'X_Maximum',
             'Empty_Index',
             'Sum_of_Luminosity'])
def feats(df):
        df.drop(var_drop, axis=1, inplace=True)
        return df


train=feats(train)
test=feats(test)
to_remove = var_drop
independent_cols_scaled = [col for col in independent_cols_scaled if col not in to_remove]

In [10]:
independent_cols_scaled

['Pixels_Areas',
 'Y_Perimeter',
 'Minimum_of_Luminosity',
 'Maximum_of_Luminosity',
 'Length_of_Conveyer',
 'Steel_Plate_Thickness',
 'Square_Index',
 'Edges_X_Index',
 'Edges_Y_Index',
 'LogOfAreas',
 'Log_X_Index',
 'Log_Y_Index',
 'Orientation_Index',
 'Y_Maximum_scaled',
 'Pixels_Areas_scaled',
 'X_Perimeter_scaled',
 'Minimum_of_Luminosity_scaled',
 'Maximum_of_Luminosity_scaled',
 'Length_of_Conveyer_scaled',
 'TypeOfSteel_A300_scaled',
 'Steel_Plate_Thickness_scaled',
 'Empty_Index_scaled',
 'Square_Index_scaled',
 'Edges_X_Index_scaled',
 'Edges_Y_Index_scaled',
 'LogOfAreas_scaled',
 'Log_X_Index_scaled',
 'Log_Y_Index_scaled',
 'Orientation_Index_scaled']

In [11]:
train.columns

Index(['Pixels_Areas', 'Y_Perimeter', 'Minimum_of_Luminosity',
       'Maximum_of_Luminosity', 'Length_of_Conveyer', 'Steel_Plate_Thickness',
       'Square_Index', 'Edges_X_Index', 'Edges_Y_Index', 'LogOfAreas',
       'Log_X_Index', 'Log_Y_Index', 'Orientation_Index', 'Pastry',
       'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults',
       'Y_Maximum_scaled', 'Pixels_Areas_scaled', 'X_Perimeter_scaled',
       'Minimum_of_Luminosity_scaled', 'Maximum_of_Luminosity_scaled',
       'Length_of_Conveyer_scaled', 'TypeOfSteel_A300_scaled',
       'Steel_Plate_Thickness_scaled', 'Empty_Index_scaled',
       'Square_Index_scaled', 'Edges_X_Index_scaled', 'Edges_Y_Index_scaled',
       'LogOfAreas_scaled', 'Log_X_Index_scaled', 'Log_Y_Index_scaled',
       'Orientation_Index_scaled'],
      dtype='object')

In [12]:
dependent_variables = ['Pastry','Z_Scratch','K_Scatch','Stains','Dirtiness','Bumps','Other_Faults']

for dv in dependent_variables:
    formula = f'{dv} ~ {" + ".join(independent_cols_scaled)}'

    data = ols(formula, data=train).fit()
    p_value = pd.DataFrame(sm.stats.anova_lm(data, typ=1))
    
    print(f"Dependent Variable: {dv}")
    print(p_value[p_value['PR(>F)'] < 0.05].sort_values(by='PR(>F)', ascending=True))
    print("\n")

Dependent Variable: Pastry
                          df     sum_sq    mean_sq           F         PR(>F)
Edges_Y_Index            1.0  37.744499  37.744499  607.907995  3.606672e-132
Square_Index             1.0  32.290274  32.290274  520.062962  1.321126e-113
Length_of_Conveyer       1.0  22.430363  22.430363  361.260511   8.090988e-80
Log_X_Index              1.0  14.406807  14.406807  232.034158   4.328616e-52
Pixels_Areas             1.0  13.894658  13.894658  223.785551   2.595376e-50
Edges_X_Index            1.0  11.671859  11.671859  187.985441   1.389050e-42
Minimum_of_Luminosity    1.0   8.936650   8.936650  143.932523   4.825268e-33
TypeOfSteel_A300_scaled  1.0   8.696117   8.696117  140.058537   3.344813e-32
Log_Y_Index              1.0   3.356947   3.356947   54.066557   2.015975e-13
Empty_Index_scaled       1.0   2.232811   2.232811   35.961369   2.048713e-09
Y_Perimeter              1.0   1.708529   1.708529   27.517345   1.573441e-07
Maximum_of_Luminosity    1.0   1.3964

In [13]:
# dependent_variables = ['Pastry']

# for dv in dependent_variables:
#     formula = f'{dv} ~ {" + ".join(independent_cols)}'

#     data = ols(formula, data=train).fit()
#     p_value = pd.DataFrame(sm.stats.anova_lm(data, typ=1))
    
#     print(f"Dependent Variable: {dv}")
#     print(p_value[p_value['PR(>F)'] < 0.05].sort_values(by='PR(>F)', ascending=True))
#     print("\n")

In [14]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
X = train.drop(['Pastry','Z_Scratch','K_Scatch','Stains','Dirtiness','Bumps','Other_Faults'], axis=1)
y = train[['Pastry','Z_Scratch','K_Scatch','Stains','Dirtiness','Bumps','Other_Faults']]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)


In [16]:
# import optuna
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.multioutput import MultiOutputClassifier
# from sklearn.metrics import accuracy_score
# from sklearn.model_selection import train_test_split

# # Define the objective function for Optuna to optimize
# def objective(trial):
#     # Define hyperparameters to be tuned
#     param_space = {
#         'n_estimators': trial.suggest_int('n_estimators', 50, 250, step=50),
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2),
#         'max_depth': trial.suggest_int('max_depth', 3, 7),
#     }

#     # Initialize XGBoost classifier
#     classifier = GradientBoostingClassifier(**param_space, validation_fraction=0.1, n_iter_no_change=5, random_state=42)

#     # Create a MultiOutputClassifier
#     multi_output_classifier = MultiOutputClassifier(classifier, n_jobs=-1)

#     # Fit the model
#     multi_output_classifier.fit(X_train, y_train)

#     # Make predictions on the validation set
#     y_pred = multi_output_classifier.predict(X_val)

#     # Calculate accuracy score
#     accuracy = accuracy_score(y_val, y_pred)

#     return accuracy

# # Split data into train and validation sets
# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# # Define Optuna study
# study = optuna.create_study(direction='maximize')
# study.optimize(objective, n_trials=100)

# # Get best parameters
# best_params = study.best_params
# print("Best parameters:", best_params)




In [17]:
import xgboost as Xgb
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.ensemble import GradientBoostingClassifier

In [18]:
op_params = {'n_estimators': 50, 'learning_rate': 0.12002152645991093, 'max_depth': 7}

# Initialize XGBoost classifier with best parameters
best_classifier =GradientBoostingClassifier(**op_params, validation_fraction=0.1, n_iter_no_change=5, random_state=42)

# Create a MultiOutputClassifier
best_multi_output_classifier = MultiOutputClassifier(best_classifier, n_jobs=-1)

# Fit the model with the entire training data
best_multi_output_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_multi_output_classifier.predict(X_test)

# Evaluate the model's performance
model_score = accuracy_score(y_test, y_pred)
print(f"Model Score: {model_score}")

Model Score: 0.3951612903225806


In [19]:

# Initialize a multi-output classifier with a base classifier (RandomForestClassifier in this case)
classifier = GradientBoostingClassifier()

# Create a MultiOutputClassifier
multi_output_classifier = MultiOutputClassifier(classifier, n_jobs=-1)

# Fit the model
multi_output_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = multi_output_classifier.predict(X_test)

# Evaluate the model's performance
model_score = multi_output_classifier.score(X_test, y_test)
print(f"Model Score: {model_score}")

Model Score: 0.39021852237252863


In [20]:
import pandas as pd
test

Pixels_Areas  Y_Perimeter  Minimum_of_Luminosity  \
id                                                        
19219           659           46                     67   
19220           370           28                     92   
19221           289           32                    101   
19222            80           11                    107   
19223           140           15                    103   
...             ...          ...                    ...   
32028           313           37                     79   
32029            59           18                    113   
32030         16584          522                     24   
32031           386           34                     66   
32032          5480          383                     38   

       Maximum_of_Luminosity  Length_of_Conveyer  Steel_Plate_Thickness  \
id                                                                        
19219                    127                1656                    150   
19220                    132                1354                     40   
19221                    134                1360                     40   
19222                    140                1690                    100   
19223                    134                1688                     60   
...                      ...                 ...                    ...   
32028                    103                1353                     70   
32029                    141                1362                     40   
32030                    143                1400                     40   
32031                    124                1364                     40   
32032                    141                1356                     40   

       Square_Index  Edges_X_Index  Edges_Y_Index  LogOfAreas  ...  \
id                                                             ...   
19219        0.3273         0.5652         1.0000      2.8410  ...   
19220        0.0938         0.2414         1.0000      2.5682  ...   
19221        0.4762         0.6000         0.7500      2.4609  ...   
19222        0.8182         0.8000         1.0000      1.9031  ...   
19223        0.4286         0.8421         0.5333      2.1461  ...   
...             ...            ...            ...         ...  ...   
32028        0.2339         0.4063         0.9194      2.4955  ...   
32029        0.2778         0.7778         1.0000      1.7708  ...   
32030        0.9371         0.2199         0.4097      4.2525  ...   
32031        0.1539         0.2407         1.0000      2.5866  ...   
32032        0.8838         0.2439         0.3931      3.7388  ...   

       TypeOfSteel_A300_scaled  Steel_Plate_Thickness_scaled  \
id                                                             
19219                      0.0                      0.423077   
19220                      0.0                      0.000000   
19221                      0.0                      0.000000   
19222                      1.0                      0.230769   
19223                      1.0                      0.076923   
...                        ...                           ...   
32028                      0.0                      0.115385   
32029                      0.0                      0.000000   
32030                      0.0                      0.000000   
32031                      0.0                      0.000000   
32032                      0.0                      0.000000   

       Empty_Index_scaled  Square_Index_scaled  Edges_X_Index_scaled  \
id                                                                     
19219            0.527871             0.321670              0.558847   
19220            0.445930             0.086216              0.230317   
19221            0.672129             0.471816              0.594156   
19222            0.359353             0.816678              0.797078   
19223            0.282372             0.423818              0.839793   
...            

In [21]:
preds_test = best_multi_output_classifier.predict(test)
print(preds_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [22]:


# Save test predictions to file
output = pd.DataFrame({'id': test.index,
                       'Pastry': preds_test[:, 0],         
                       'Z_Scratch': preds_test[:, 1],
                       'K_Scatch': preds_test[:, 2],
                       'Stains': preds_test[:, 3],
                       'Dirtiness': preds_test[:, 4],
                       'Bumps': preds_test[:, 5],
                       'Other_Faults': preds_test[:, 6]})

output.to_csv('submission.csv', index=False)
